# SPDX-FileCopyrightText: 2024 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: eudiw-wallet-issuer-poc workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
jobs:
  commitlint:
    permissions:
      contents: read
    uses: ./.github/workflows/commitlint.yml
  dependencyreviewlint:
    permissions:
      contents: read
    uses: ./.github/workflows/dependencyreview.yml
  misclint:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/misclint.yml
  test:
    permissions:
      contents: read
    needs: [commitlint, misclint]
    uses: ./.github/workflows/test.yml
  publish-container-image: # only on semver tag
    permissions:
      contents: read
      packages: write
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/publishimage.yml
