# SPDX-FileCopyrightText: 2024 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: Publish Container Image

on: [workflow_call] # yamllint disable-line rule:truthy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eudiw-wallet-issuer-poc

jobs:
  publish-container:
    name: Build and Publish Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Configure QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configure Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Build Platform Support
        run: |
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Authenticate with Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Image Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=raw,value={{branch}},priority=1,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{version}},priority=2
            type=raw,value=${{ env.IMAGE_NAME }}-{{branch}}-{{date 'YYYYMMDD'}}-{{sha}},priority=31,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=${{ env.IMAGE_NAME }}-{{tag}}-{{date 'YYYYMMDD'}}-{{sha}},priority=32,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and Push Container Image
        uses: docker/build-push-action@v6
        with:
          file: Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}