# SPDX-FileCopyrightText: 2024 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
name: Gradle Test

on: [workflow_call]  # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['21'] 
        os: [ubuntu-latest]

    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 #v2.10.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v4.2.1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'  # Popular Java distribution
          cache: 'gradle'  # Enables Gradle caching

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3 #v3.5.0

      - name: Grant execute permission for gradlew
        run: chmod +x issuer/gradlew

      - name: Run tests
        run: |
          cd ./issuer
          ./gradlew test --no-daemon

      # Optional: Publish test results
      # - name: Publish Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@f355d34d53ad4e7f506f699478db2dd71da9de5f # v2.15.1
      #   if: always()  # Run even if tests fail
      #   with:
      #     files: "**/build/test-results/test/TEST-*.xml"